name: auto_id
description: Application for EME-IH Borg.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  #firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.12
  firebase_database: ^9.0.4
  cloud_firestore: ^3.1.11
  google_sign_in: ^5.2.4
  firebase_storage: ^10.2.7
  firebase_messaging: ^11.2.13
  firebase_analytics: ^9.1.5
  firebase_crashlytics: ^2.8.1
  #bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  # web services
  dio: ^4.0.6
  connectivity_plus: ^2.2.1
  #local data
  shared_preferences: ^2.0.13
  #widget
  syncfusion_flutter_charts: ^20.1.59
  syncfusion_flutter_sliders: ^20.1.52
  flutter_typeahead: ^4.0.0
  fluttertoast: ^8.0.8
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^1.2.4
  im_stepper: ^0.1.3
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  percent_indicator: ^4.2.0
  # for images
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8 # not web supported
  cached_network_image: ^3.2.0 # not web supported
  lottie: ^1.3.0
  photo_view:
    git: https://github.com/bluefireteam/photo_view
  # QR Images
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0  # not web supported
  r_scan: ^0.1.6+1 # not web supported
  mobile_scanner: ^2.0.0
  # for operation
  intl: ^0.17.0
  permission_handler: ^9.2.0 # not web supported
  flutter_windowmanager: ^0.2.0 # not web supported
  file_picker: ^4.6.1
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/lottie/

